SELECT * FROM dbo.PriceHistory WHERE InventoryNum = 5;

EXEC dbo.procXMLDataUpdate
'
<PRICEROW>
 <PRICEHISTORY>
    <INVENTORYNUM>5</INVENTORYNUM>
	<DESCRIPTION>Air Filter Performance</DESCRIPTION>
	<DATEPREVIOUSPRICE>2016-01-04</DATEPREVIOUSPRICE>
	<DATECURRENTPRICE>2016-09-06</DATECURRENTPRICE>
	<DATEENDPRICE>NULL</DATEENDPRICE>
	<INVENTORYPRICE>61.95</INVENTORYPRICE>
 <PRICEHISTORY>
</PRICEROW>
';





