CREATE DATABASE OpenXMLMigration
GO

USE OpenXMLMigration
GO

CREATE TABLE XMLwithOpenXML
(
ID INT IDENTITY PRIMARY KEY,
XMLDATA XML,
LOADEDDATETIME DATETIME
)

INSERT INTO XMLwithOpenXML(XMLDATA, LOADEDDATETIME)
SELECT CONVERT(XML, BULKCOLUMN) AS BULKCOLUMN, GETDATE()
FROM OPENROWSET(BULK 'C:OpenXMLMigration.xml', SINGLE_BLOG) AS x;

SELECT * FROM XMLwithOpenXML
