Declare @x xml
Set @x =

'<PRICEHISTORY>
	<PRICEHISTORY>
		<INVENTORYNUM>769752</INVENTORYNUM>
		<DESCRIPTION>16GB SD MEMORY CARD</DESCRIPTION>
		<DATEPREVIOUSPRICE>08/15/16</DATEPREVIOUSPRICE>
		<DATECURRENTPRICE>09/11/16</DATECURRENTPRICE>
		<DATEENDPRICE>09/12/16</DATEENDPRICE>
		<INVENTORYPRICE>6.99</INVENTORYPRICE>
	</PRICEHISTORY>	
</PRICEHISTORY>'

 
Set @x.modify('replace value of
/PRICEHISTORY[1]/PRICEHISTORY[1]/DESCRIPTION[1]/text()[1]
with "HARD DRIVE" ')


Select @x
;
